In [7]:
from google.colab import drive
drive.mount("/content/drive")

import os
os.chdir('/content/drive/MyDrive/Stock/Daily')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
! pip install FinMind

Requirement already satisfied: FinMind in /usr/local/lib/python3.13/dist-packages (2.0.11)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (2.2.3)
Requirement already satisfied: numpy<3.0.0,>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from FinMind) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (2.13.5)
Requirement already satisfied: ta<1.0.0,>=0.11.0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (0.11.0)
Requirement already satisfied: lxml<7.0.0,>=4.6.3 in /usr/local/lib/python3.13/dist-packages (from FinMind) (6.1.3)
Requirement already satisfied: pyecharts<2.0.0,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (1.9.1)
Requirement already satisfied: ipython<8.0.0,>=7.16.1 in /usr/local/lib/python3.13/dist-packages (from FinMind) (7.34.0)
Requirement already satisfied: loguru<1.0.0,>=0.5.3 in /usr/local/lib/python3.13/dist-packages (from FinMind) (0.7.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.7.4.post0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (3.14.3)
Requirement already satisfied: importlib-metadata<9.0.0,>=4.8.1 in /usr/local/lib/python3.13/dist-packages (from FinMind) (8.9.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (4.16.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from FinMind) (4.67.3)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.13/dist-packages (from FinMind) (1.6.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.13/dist-packages (from FinMind) (23.0.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.13/dist-packages (from FinMind) (1.3.1)
Requirement already satisfied: tomli in /usr/local/lib/python3.13/dist-packages (from FinMind) (2.5.0)
Requirement already satisfied: async-timeout in /usr/local/lib/python3.13/dist-packages (from FinMind) (5.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.7.4.post0->FinMind) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.7.4.post0->FinMind) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.7.4.post0->FinMind) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.7.4.post0->FinMind) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.7.4.post0->FinMind) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.7.4.post0->FinMind) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.7.4.post0->FinMind) (1.25.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib-metadata<9.0.0,>=4.8.1->FinMind) (4.1.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (80.10.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (0.20.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (3.0.53)
Requirement already satisfied: pygments in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (2.21.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.13/dist-packages (from ipython<8.0.0,>=7.16.1->FinMind) (4.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<3.0.0,>=2.0.0->FinMind) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<3.0.0,>=2.0.0->FinMind) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<3.0.0,>=2.0.0->FinMind) (2026.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->FinMind) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->FinMind) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->FinMind) (0.4.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from pyecharts<2.0.0,>=1.9.0->FinMind) (3.1.6)
Requirement already satisfied: prettytable in /usr/local/lib/python3.13/dist-packages (from pyecharts<2.0.0,>=1.9.0->FinMind) (3.18.0)
Requirement already satisfied: simplejson in /usr/local/lib/python3.13/dist-packages (from pyecharts<2.0.0,>=1.9.0->FinMind) (4.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->FinMind) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->FinMind) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->FinMind) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->FinMind) (2026.7.22)
Requirement already satisfied: parso<0.9.0,>=0.8.7 in /usr/local/lib/python3.13/dist-packages (from jedi>=0.16->ipython<8.0.0,>=7.16.1->FinMind) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.13/dist-packages (from pexpect>4.3->ipython<8.0.0,>=7.16.1->FinMind) (0.7.0)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.13/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<8.0.0,>=7.16.1->FinMind) (0.9.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->FinMind) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->pyecharts<2.0.0,>=1.9.0->FinMind) (3.0.3)

In [9]:
! pip install TA-Lib

Requirement already satisfied: TA-Lib in /usr/local/lib/python3.13/dist-packages (0.8.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from TA-Lib) (2.1.3)

# 迴圈

In [ ]:
from FinMind.data import DataLoader
import pandas as pd
import numpy as np
import talib
from datetime import datetime
import matplotlib.pyplot as plt
import os

api = DataLoader()
api.login_by_token(api_token="")
# api.login_by_token(api_token="你的API_TOKEN")

current_time = datetime.now().strftime("%Y-%m-%d")
end_date = current_time
start_date = "2020-01-01"
end_date = end_date
print(end_date)

# stock_id="6257"
# df = api.taiwan_stock_daily(
#     stock_id=stock_id,
#     start_date=start_date,
#     end_date=end_date)

# df.to_csv(f"{stock_id}.csv", index=False)

stock_list = ["2327", "2492", "3026", "3090",
              "1519", "1513", "1503", "1514",
              "2382", "2303", "2317", "2327",
              "2344", "2337", "6770", "2408", "3006",
              "3491", "2313", "6285", "2312",
              "2330", "2317", "2382", "3231", "2308", "2368", "2449", "2454", "2303",
              "2603", "2609", "2615", "2645",
              "6257"]

for stock_id in stock_list:
    df = api.taiwan_stock_daily(
        stock_id=stock_id,
        start_date=start_date,
        end_date=end_date)

    original_len = len(df)
    abnormal = df[df["close"].isna() | (df["close"] <= 0)]
    if len(abnormal) > 0:
        print(f"\n{stock_id} 發現 {len(abnormal)} 筆 Close 異常：")
        display(abnormal[["date", "close"]])

    df = df[df["close"].notna() & (df["close"] > 0)].copy()
    df = df.reset_index(drop=True)

    df.to_csv(f"{stock_id}.csv", index=False)
    print(
        f"{stock_id}：原始 {original_len} 筆 → "
        f"保留 {len(df)} 筆 → "
        f"移除 {original_len - len(df)} 筆")

    df.to_csv(f"{stock_id}.csv", index=False)

2026-10-14 11:32:58.399 | INFO     | FinMind.data.finmind_api:login_by_token:89 - Login success
2026-10-14 11:32:58.551 | INFO     | FinMind.data.finmind_api:login_by_token:89 - Login success
2026-10-14 11:32:58.554 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2327

2026-10-14

2327 發現 1 筆 Close 異常：

           date  close
360  2021-06-30    0.0

2026-10-14 11:32:59.488 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2492

2327：原始 1633 筆 → 保留 1632 筆 → 移除 1 筆

2026-10-14 11:32:59.851 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 3026

2492：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:00.214 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 3090

3026：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

3090 發現 1 筆 Close 異常：

            date  close
1342  2025-07-15    0.0

3090：原始 1647 筆 → 保留 1646 筆 → 移除 1 筆

2026-10-14 11:33:00.705 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 1519
2026-10-14 11:33:01.228 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 1513

1519：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:01.567 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 1503

1513：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:01.977 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 1514

1503：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:02.333 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2382

1514：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:02.671 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2303

2382：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:03.008 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2317

2303：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2317 發現 1 筆 Close 異常：

            date  close
1353  2025-07-30    0.0

2026-10-14 11:33:03.414 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2327

2317：原始 1647 筆 → 保留 1646 筆 → 移除 1 筆

2327 發現 1 筆 Close 異常：

           date  close
360  2021-06-30    0.0

2026-10-14 11:33:03.883 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2344

2327：原始 1633 筆 → 保留 1632 筆 → 移除 1 筆

2026-10-14 11:33:04.309 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2337

2344：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:04.800 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 6770

2337：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:05.223 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2408

6770：原始 1419 筆 → 保留 1419 筆 → 移除 0 筆

2026-10-14 11:33:05.913 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 3006

2408：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:06.522 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 3491

3006：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

3491 發現 2 筆 Close 異常：

            date  close
1017  2024-03-13    0.0
1584  2026-07-15    0.0

2026-10-14 11:33:06.805 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2313

3491：原始 1647 筆 → 保留 1645 筆 → 移除 2 筆

2026-10-14 11:33:07.103 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 6285

2313：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:07.438 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2312

6285：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:07.751 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2330

2312：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:08.087 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2317

2330：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2317 發現 1 筆 Close 異常：

            date  close
1353  2025-07-30    0.0

2026-10-14 11:33:08.498 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2382

2317：原始 1647 筆 → 保留 1646 筆 → 移除 1 筆

2026-10-14 11:33:09.003 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 3231

2382：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:09.319 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2308

3231：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:09.640 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2368

2308：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:09.948 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2449

2368：原始 1640 筆 → 保留 1640 筆 → 移除 0 筆

2449 發現 1 筆 Close 異常：

            date  close
1047  2024-04-26    0.0

2026-10-14 11:33:10.279 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2454

2449：原始 1647 筆 → 保留 1646 筆 → 移除 1 筆

2026-10-14 11:33:10.597 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2303

2454：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:10.973 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2603

2303：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:11.281 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2609

2603：原始 1640 筆 → 保留 1640 筆 → 移除 0 筆

2026-10-14 11:33:11.571 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2615

2609：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:11.917 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 2645

2615：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

2026-10-14 11:33:12.180 | INFO     | FinMind.data.finmind_api:get_data:170 - download Dataset.TaiwanStockPrice, data_id: 6257

2645：原始 1131 筆 → 保留 1131 筆 → 移除 0 筆
6257：原始 1647 筆 → 保留 1647 筆 → 移除 0 筆

In [15]:
df_match = pd.read_csv("record.csv")
strategy_map = {
    "KD 黃金交叉／死亡交叉": ["KD黃金交叉", "KD死亡交叉"],
    "MACD Histogram": ["MACD_Hist由負翻正", "MACD_Hist由正翻負"],
    "MACD": ["MACD_Hist由負翻正", "MACD_Hist由正翻負"],
    "布林通道": ["BB中線突破", "BB上線跌破"],
    "SMA 黃金交叉／死亡交叉": ["SMA黃金交叉", "SMA死亡交叉"],
    "KD 超買／超賣": ["KD超買", "KD超賣"],
    "RSI 超買／超賣": ["RSI超買", "RSI超賣"]
}
name_to_id = {
    "中興電": "1513", "華城": "1519", "士電": "1503", "亞力": "1514",
    "鴻海": "2317", "緯創": "3231", "台積電": "2330", "廣達": "2382",
    "金像電": "2368", "京元電子": "2449", "聯電": "2303", "國巨": "2327",
    "華新科": "2492", "禾伸堂": "3026", "日電貿": "3090", "華邦電": "2344",
    "旺宏": "2337", "力積電": "6770", "南亞科": "2408", "晶豪科": "3006",
    "昇達科": "3491", "華通": "2313", "啟碁": "6285", "金寶": "2312",
    "長榮": "2603", "萬海": "2615", "陽明": "2609", "長榮航太": "2645",
    "矽格": "6257"
}
df_match["標的"] = df_match["標的"].astype(str).str.strip()
df_match["策略"] = df_match["策略"].astype(str).str.strip()

stock_strategy = {}
for _, row in df_match.iterrows():
    name = row["標的"]
    stock_id = next((code for key, code in name_to_id.items() if key in name), None)
    if stock_id:
        stock_strategy[stock_id] = strategy_map.get(row["策略"], [])

os.makedirs("Image", exist_ok=True)
os.makedirs("Result", exist_ok=True)
signal_summary = []

for stock_id in stock_list:

    print("=" * 80)
    print(f"{stock_id}")
    print("=" * 80)

    # 讀取資料
    df = pd.read_csv(f"{stock_id}.csv")
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").reset_index(drop=True)

    # KD
    df["K"], df["D"] = talib.STOCH(
        high=df["max"],
        low=df["min"],
        close=df["close"],
        fastk_period=9,
        slowk_period=3,
        slowk_matype=0,
        slowd_period=3,
        slowd_matype=0)

    # MACD
    df["MACD"], df["MACD_Signal"], df["MACD_Hist"] = talib.MACD(
        df["close"],
        fastperiod=12,
        slowperiod=26,
        signalperiod=9)

    # Bollinger Bands
    df["BB_Upper"], df["BB_Middle"], df["BB_Lower"] = talib.BBANDS(
        df["close"],
        timeperiod=20,
        nbdevup=2,
        nbdevdn=2,
        matype=0)

    # RSI
    df["RSI_7"] = talib.RSI(df["close"], timeperiod=7)
    df["RSI_14"] = talib.RSI(df["close"], timeperiod=14)

    # SMA
    df["SMA5"] = talib.SMA(df["close"], timeperiod=5)
    df["SMA10"] = talib.SMA(df["close"], timeperiod=10)
    df["SMA20"] = talib.SMA(df["close"], timeperiod=20)

    df = df.tail(60).reset_index(drop=True)

    # 畫圖
    fig, (ax1, ax2, ax3, ax4) = plt.subplots(
        4, 1,
        figsize=(14, 10),
        sharex=True,
        gridspec_kw={"height_ratios":[3, 1, 1, 1]})

    # 股價 + Bollinger Bands
    ax1.plot(df["date"], df["close"], label="Close")
    ax1.plot(df["date"], df["BB_Upper"], label="BB Upper")
    ax1.plot(df["date"], df["BB_Middle"], label="BB Middle")
    ax1.plot(df["date"], df["BB_Lower"], label="BB Lower")
    ax1.set_title(f"{stock_id} Price")
    ax1.legend()
    ax1.grid(True)

    # MACD
    ax2.plot(df["date"], df["MACD"], label="MACD")
    ax2.plot(df["date"], df["MACD_Signal"], label="Signal")
    colors = ["red" if x >= 0 else "green" for x in df["MACD_Hist"]]
    ax2.bar(df["date"], df["MACD_Hist"], color=colors, width=1)
    ax2.axhline(0, color="black")
    ax2.set_ylabel("MACD")
    ax2.legend()
    ax2.grid(True)

    # KD
    ax3.plot(df["date"], df["K"], label="K")
    ax3.plot(df["date"], df["D"], label="D")
    ax3.axhline(80, linestyle="--")
    ax3.axhline(30, linestyle="--")
    ax3.set_ylim(0,100)
    ax3.set_ylabel("KD")
    ax3.set_xlabel("Date")
    ax3.legend()
    ax3.grid(True)

    # RSI
    ax4.plot(df["date"], df["RSI_7"], label="RSI 7")
    ax4.plot( df["date"], df["RSI_14"], label="RSI 14")
    ax4.axhline(70, linestyle="--")
    ax4.axhline(30, linestyle="--")
    ax4.set_ylim(0, 100)
    ax4.set_ylabel("RSI")
    ax4.set_xlabel("Date")
    ax4.legend()
    ax4.grid(True)

    plt.tight_layout()

    # 儲存圖片
    plt.savefig(
        f"Image/{stock_id}_technical_analysis.png",
        dpi=300,
        bbox_inches="tight")

    plt.close()

    result_df = df[["date", "open", "max", "min", "close"]].copy()

    # KD
    result_df["KD黃金交叉"] = ((df["K"].shift(1) <= df["D"].shift(1)) & (df["K"] > df["D"])).astype(int)
    result_df["KD死亡交叉"] = ((df["K"].shift(1) >= df["D"].shift(1)) & (df["K"] < df["D"])).astype(int)
    result_df["KD超買"] = ((df["K"] > 80) & (df["D"] > 80)).astype(int)
    result_df["KD超賣"] = ((df["K"] < 30) & (df["D"] < 30)).astype(int)

    # MACD Histogram
    result_df["MACD_Hist由負翻正"] = ((df["MACD_Hist"].shift(1) <= 0) & (df["MACD_Hist"] > 0)).astype(int)
    result_df["MACD_Hist由正翻負"] = ((df["MACD_Hist"].shift(1) >= 0) & (df["MACD_Hist"] < 0)).astype(int)

    # Bollinger Bands
    result_df["BB中線突破"] = ((df["close"].shift(1) <= df["BB_Middle"].shift(1)) & (df["close"] > df["BB_Middle"])).astype(int)
    result_df["BB上線跌破"] = ((df["close"].shift(1) >= df["BB_Upper"].shift(1)) & (df["close"] < df["BB_Upper"])).astype(int)

    # RSI
    result_df["RSI黃金交叉"] = ((df["RSI_7"].shift(1) <= df["RSI_14"].shift(1)) & (df["RSI_7"] > df["RSI_14"])).astype(int)
    result_df["RSI死亡交叉"] = ((df["RSI_7"].shift(1) >= df["RSI_14"].shift(1)) & (df["RSI_7"] < df["RSI_14"])).astype(int)
    result_df["RSI超買"] = ( (df["RSI_7"] > 70) & (df["RSI_14"] > 70)).astype(int)
    result_df["RSI超賣"] = ((df["RSI_7"] < 30) & (df["RSI_14"] < 30)).astype(int)

    # SMA
    result_df["SMA黃金交叉"] = ((df["SMA5"].shift(1) <= df["SMA20"].shift(1)) & (df["SMA5"] > df["SMA20"])).astype(int)
    result_df["SMA死亡交叉"] = ((df["SMA5"].shift(1) >= df["SMA20"].shift(1)) & (df["SMA5"] < df["SMA20"])).astype(int)

    result_df["K"] = df["K"]
    result_df["D"] = df["D"]
    result_df["MACD"] = df["MACD"]
    result_df["MACD_Signal"] = df["MACD_Signal"]
    result_df["MACD_Hist"] = df["MACD_Hist"]
    result_df["BB_Upper"] = df["BB_Upper"]
    result_df["BB_Middle"] = df["BB_Middle"]
    result_df["BB_Lower"] = df["BB_Lower"]
    result_df["RSI_7"] = df["RSI_7"]
    result_df["RSI_14"] = df["RSI_14"]
    result_df["SMA5"] = df["SMA5"]
    result_df["SMA10"] = df["SMA10"]

    result_df.to_csv(f"Result/{stock_id}_result.csv", index=False, encoding="utf-8-sig")

    # 最近幾天觸發訊號
    signal_cols = [
    "KD黃金交叉",
    "KD死亡交叉",
    "KD超買",
    "KD超賣",
    "MACD_Hist由負翻正",
    "MACD_Hist由正翻負",
    "BB中線突破",
    "BB上線跌破",
    "RSI黃金交叉",
    "RSI死亡交叉",
    "RSI超買",
    "RSI超賣",
    "SMA黃金交叉",
    "SMA死亡交叉"]

    last1 = result_df.tail(3)
    allowed_signals = stock_strategy.get(stock_id, [])
    for _, row in last1.iterrows():
      for signal in allowed_signals:
        if signal in result_df.columns and row[signal] == 1:
          signal_summary.append({
              "日期": row["date"].strftime("%Y-%m-%d"),
              "股票代號": stock_id,
              "訊號": signal,
              "收盤價": row["close"]
          })

print("\n" + "=" * 80)
print("最近幾天技術訊號整理")

summary_df = pd.DataFrame(signal_summary)
if summary_df.empty:
    print("最近幾天沒有適合策略觸發訊號")
else:
    summary_df = summary_df.sort_values(["股票代號", "日期"]).reset_index(drop=True)
    print(summary_df.to_string(index=False))

summary_df.to_csv("Result/LastDays_Signal_Summary.csv", index=False, encoding="utf-8-sig")

================================================================================
2327
================================================================================
================================================================================
2492
================================================================================
================================================================================
3026
================================================================================
================================================================================
3090
================================================================================
================================================================================
1519
================================================================================
================================================================================
1513
================================================================================
================================================================================
1503
================================================================================
================================================================================
1514
================================================================================
================================================================================
2382
================================================================================
================================================================================
2303
================================================================================
================================================================================
2317
================================================================================
================================================================================
2327
================================================================================
================================================================================
2344
================================================================================
================================================================================
2337
================================================================================
================================================================================
6770
================================================================================
================================================================================
2408
================================================================================
================================================================================
3006
================================================================================
================================================================================
3491
================================================================================
================================================================================
2313
================================================================================
================================================================================
6285
================================================================================
================================================================================
2312
================================================================================
================================================================================
2330
================================================================================
================================================================================
2317
================================================================================
================================================================================
2382
================================================================================
================================================================================
3231
================================================================================
================================================================================
2308
================================================================================
================================================================================
2368
================================================================================
================================================================================
2449
================================================================================
================================================================================
2454
================================================================================
================================================================================
2303
================================================================================
================================================================================
2603
================================================================================
================================================================================
2609
================================================================================
================================================================================
2615
================================================================================
================================================================================
2645
================================================================================
================================================================================
6257
================================================================================

================================================================================
最近幾天技術訊號整理
        日期 股票代號            訊號   收盤價
2026-10-13 1513        KD死亡交叉 165.5
2026-10-12 1514        KD死亡交叉 105.0
2026-10-13 1519        KD死亡交叉 663.0
2026-10-12 2303       SMA死亡交叉 145.5
2026-10-12 2303       SMA死亡交叉 145.5
2026-10-13 2337          KD超賣 106.5
2026-10-14 2337          KD超賣 110.0
2026-10-14 2344       SMA死亡交叉 165.0
2026-10-12 2382          KD超賣 322.0
2026-10-12 2382          KD超賣 322.0
2026-10-13 2382          KD超賣 323.0
2026-10-13 2382          KD超賣 323.0
2026-10-14 2382          KD超賣 323.0
2026-10-14 2382          KD超賣 323.0
2026-10-13 2603 MACD_Hist由負翻正 264.0
2026-10-12 2609       SMA黃金交叉  63.6
2026-10-13 2615 MACD_Hist由負翻正 121.5
2026-10-14 3090        KD黃金交叉 183.5
2026-10-14 3231 MACD_Hist由正翻負 187.0
2026-10-12 6257          KD超買 287.0
2026-10-13 6257          KD超買 279.0
2026-10-13 6770       SMA死亡交叉  67.5